// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIgwA7D_Kx08oOvgkAR6ZuuB7yL9kb_kQ',
    appId: '1:326784541342:web:72d1961744cabb34ead18f',
    messagingSenderId: '326784541342',
    projectId: 'stanag-app-prod',
    authDomain: 'stanag-app-prod.firebaseapp.com',
    storageBucket: 'stanag-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqom75A7Ag0X_wC1ZruqRD88lS1iYgECE',
    appId: '1:326784541342:android:d746623d41710863ead18f',
    messagingSenderId: '326784541342',
    projectId: 'stanag-app-prod',
    storageBucket: 'stanag-app-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZIaAD9h_P2sj55FAEpvb_UukkKY8jqM0',
    appId: '1:326784541342:ios:b76b37769666cd43ead18f',
    messagingSenderId: '326784541342',
    projectId: 'stanag-app-prod',
    storageBucket: 'stanag-app-prod.firebasestorage.app',
    iosBundleId: 'com.example.stanagApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZIaAD9h_P2sj55FAEpvb_UukkKY8jqM0',
    appId: '1:326784541342:ios:b76b37769666cd43ead18f',
    messagingSenderId: '326784541342',
    projectId: 'stanag-app-prod',
    storageBucket: 'stanag-app-prod.firebasestorage.app',
    iosBundleId: 'com.example.stanagApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIgwA7D_Kx08oOvgkAR6ZuuB7yL9kb_kQ',
    appId: '1:326784541342:web:96bb2ce432e8b8edead18f',
    messagingSenderId: '326784541342',
    projectId: 'stanag-app-prod',
    authDomain: 'stanag-app-prod.firebaseapp.com',
    storageBucket: 'stanag-app-prod.firebasestorage.app',
  );
}
