// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4JpQYMCiUN2HmGKkuMbg2XTfSTccLTQc',
    appId: '1:698772630591:web:b20bf52b98f28369b11c8a',
    messagingSenderId: '698772630591',
    projectId: 'stanag-dev',
    authDomain: 'stanag-dev.firebaseapp.com',
    storageBucket: 'stanag-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfh6X8XQ_2tEbTOtjqZNTcFtPOrStW1Kc',
    appId: '1:698772630591:android:5e39666892fd2d79b11c8a',
    messagingSenderId: '698772630591',
    projectId: 'stanag-dev',
    storageBucket: 'stanag-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBELXCoNfB-trGyRT_AImU1wREEQSDcdis',
    appId: '1:698772630591:ios:4ff0a5e4cfca617fb11c8a',
    messagingSenderId: '698772630591',
    projectId: 'stanag-dev',
    storageBucket: 'stanag-dev.firebasestorage.app',
    iosBundleId: 'com.example.stanagApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBELXCoNfB-trGyRT_AImU1wREEQSDcdis',
    appId: '1:698772630591:ios:4ff0a5e4cfca617fb11c8a',
    messagingSenderId: '698772630591',
    projectId: 'stanag-dev',
    storageBucket: 'stanag-dev.firebasestorage.app',
    iosBundleId: 'com.example.stanagApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4JpQYMCiUN2HmGKkuMbg2XTfSTccLTQc',
    appId: '1:698772630591:web:4ed5301beabb4d14b11c8a',
    messagingSenderId: '698772630591',
    projectId: 'stanag-dev',
    authDomain: 'stanag-dev.firebaseapp.com',
    storageBucket: 'stanag-dev.firebasestorage.app',
  );
}
