// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDutMf4SEpSiyBfoAEQDr0DHMsluMQ-yAg',
    appId: '1:1000137333452:web:381f63ac0cb04757dac069',
    messagingSenderId: '1000137333452',
    projectId: 'stanag-staging',
    authDomain: 'stanag-staging.firebaseapp.com',
    storageBucket: 'stanag-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpTQ3J6Y2hnfvK4iPuxpl9gCNGCwkTvOc',
    appId: '1:1000137333452:android:47b21a3c03f5b1dddac069',
    messagingSenderId: '1000137333452',
    projectId: 'stanag-staging',
    storageBucket: 'stanag-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnRaKSzjMhG1Sdle_MjoLzsd5aJtqWja4',
    appId: '1:1000137333452:ios:8fdd86bd94278b20dac069',
    messagingSenderId: '1000137333452',
    projectId: 'stanag-staging',
    storageBucket: 'stanag-staging.firebasestorage.app',
    iosBundleId: 'com.example.stanagApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnRaKSzjMhG1Sdle_MjoLzsd5aJtqWja4',
    appId: '1:1000137333452:ios:8fdd86bd94278b20dac069',
    messagingSenderId: '1000137333452',
    projectId: 'stanag-staging',
    storageBucket: 'stanag-staging.firebasestorage.app',
    iosBundleId: 'com.example.stanagApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDutMf4SEpSiyBfoAEQDr0DHMsluMQ-yAg',
    appId: '1:1000137333452:web:07e7bc9ccf76a607dac069',
    messagingSenderId: '1000137333452',
    projectId: 'stanag-staging',
    authDomain: 'stanag-staging.firebaseapp.com',
    storageBucket: 'stanag-staging.firebasestorage.app',
  );
}
