// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlNXs-3zPjopf8UO9w0R7yLqivEe8z9Qs',
    appId: '1:889848108359:web:1ca1fc3cfc227009b46862',
    messagingSenderId: '889848108359',
    projectId: 'stanag-prod',
    authDomain: 'stanag-prod.firebaseapp.com',
    storageBucket: 'stanag-prod.firebasestorage.app',
    measurementId: 'G-NYPL3WDCDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmehIIigGSRgFQXjmkCdernJP0WB-HdZc',
    appId: '1:889848108359:android:924dd5bb19327b71b46862',
    messagingSenderId: '889848108359',
    projectId: 'stanag-prod',
    storageBucket: 'stanag-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7KdsprqexTMgJxjaqrkCgBcNPtZxuC_c',
    appId: '1:889848108359:ios:dc1b4f5469d73905b46862',
    messagingSenderId: '889848108359',
    projectId: 'stanag-prod',
    storageBucket: 'stanag-prod.firebasestorage.app',
    iosBundleId: 'com.example.stanagApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7KdsprqexTMgJxjaqrkCgBcNPtZxuC_c',
    appId: '1:889848108359:ios:dc1b4f5469d73905b46862',
    messagingSenderId: '889848108359',
    projectId: 'stanag-prod',
    storageBucket: 'stanag-prod.firebasestorage.app',
    iosBundleId: 'com.example.stanagApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlNXs-3zPjopf8UO9w0R7yLqivEe8z9Qs',
    appId: '1:889848108359:web:6671a876bce655b7b46862',
    messagingSenderId: '889848108359',
    projectId: 'stanag-prod',
    authDomain: 'stanag-prod.firebaseapp.com',
    storageBucket: 'stanag-prod.firebasestorage.app',
    measurementId: 'G-S36DZHL0DC',
  );
}
